#!/usr/bin/env python3
"""Generate web vocab TS files from config.yaml (categories, sources, article picklists)."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from reader.config import (  # noqa: E402
    load_article_domains,
    load_article_types,
    load_categories,
    load_web_sources,
)


def _escape_ts_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def render_categories_ts(categories: list[str]) -> str:
    lines = [
        "// Generated by scripts/sync_web_vocab.py — do not edit manually.",
        "// Source: config.yaml categories",
        "",
        "export const CATEGORIES = [",
    ]
    for category in categories:
        lines.append(f'  "{_escape_ts_string(category)}",')
    lines.extend(
        [
            "] as const;",
            "",
            "export type Category = (typeof CATEGORIES)[number];",
            "",
            'export const UNCATEGORIZED = "Uncategorized";',
            "",
        ]
    )
    return "\n".join(lines)


def render_curation_picklists_ts(
    article_types: list[str], article_domains: list[str]
) -> str:
    lines = [
        "// Generated by scripts/sync_web_vocab.py — do not edit manually.",
        "// Source: config.yaml article_types and article_domains",
        "",
        "export const ARTICLE_TYPES = [",
    ]
    for value in article_types:
        lines.append(f'  "{_escape_ts_string(value)}",')
    lines.extend(["] as const;", "", "export const ARTICLE_DOMAINS = ["])
    for value in article_domains:
        lines.append(f'  "{_escape_ts_string(value)}",')
    lines.extend(
        [
            "] as const;",
            "",
            "export type ArticleType = (typeof ARTICLE_TYPES)[number];",
            "export type ArticleDomain = (typeof ARTICLE_DOMAINS)[number];",
            "",
        ]
    )
    return "\n".join(lines)


def render_sources_ts(sources: list) -> str:
    lines = [
        "// Generated by scripts/sync_web_vocab.py — do not edit manually.",
        "// Source: config.yaml sources (enabled only)",
        "",
        "export const SOURCES = [",
    ]
    for entry in sources:
        lines.append(f'  "{_escape_ts_string(entry.name)}",')
    lines.extend(
        [
            "] as const;",
            "",
            "export type SourceName = (typeof SOURCES)[number];",
            "",
            "export const SOURCE_DISPLAY_NAMES: Record<SourceName, string> = {",
        ]
    )
    for entry in sources:
        lines.append(
            f'  "{_escape_ts_string(entry.name)}": '
            f'"{_escape_ts_string(entry.display_name)}",'
        )
    lines.extend(
        [
            "};",
            "",
            "export function sourceDisplayName(name: SourceName): string {",
            "  return SOURCE_DISPLAY_NAMES[name];",
            "}",
            "",
            "export function sourceDisplayNameLoose(name: string): string {",
            "  return (SOURCE_DISPLAY_NAMES as Record<string, string>)[name] ?? name;",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--config",
        type=Path,
        default=REPO_ROOT / "config.yaml",
        help="Path to config.yaml (default: repo root config.yaml)",
    )
    parser.add_argument(
        "--categories-output",
        type=Path,
        default=REPO_ROOT / "apps/web/src/lib/categories.ts",
    )
    parser.add_argument(
        "--picklists-output",
        type=Path,
        default=REPO_ROOT / "apps/web/src/lib/curation-picklists.ts",
    )
    parser.add_argument(
        "--sources-output",
        type=Path,
        default=REPO_ROOT / "apps/web/src/lib/sources.ts",
    )
    args = parser.parse_args()

    categories = load_categories(args.config)
    article_types = load_article_types(args.config)
    article_domains = load_article_domains(args.config)
    sources = load_web_sources(args.config)

    args.categories_output.write_text(
        render_categories_ts(categories), encoding="utf-8"
    )
    args.picklists_output.write_text(
        render_curation_picklists_ts(article_types, article_domains),
        encoding="utf-8",
    )
    args.sources_output.write_text(render_sources_ts(sources), encoding="utf-8")

    print(
        f"Wrote {len(categories)} categories → {args.categories_output}\n"
        f"Wrote {len(article_types)} types, {len(article_domains)} domains "
        f"→ {args.picklists_output}\n"
        f"Wrote {len(sources)} sources → {args.sources_output}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
