#!/usr/bin/env python3
"""Generate apps/web/src/lib/categories.ts from config.yaml categories."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from reader.config import load_categories  # noqa: E402


def render_categories_ts(categories: list[str]) -> str:
    lines = [
        "// Generated by scripts/sync_categories.py — do not edit manually.",
        "// Source: config.yaml categories",
        "",
        "export const CATEGORIES = [",
    ]
    for category in categories:
        escaped = category.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'  "{escaped}",')
    lines.extend(
        [
            "] as const;",
            "",
            "export type Category = (typeof CATEGORIES)[number];",
            "",
            'export const UNCATEGORIZED = "Uncategorized";',
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--config",
        type=Path,
        default=REPO_ROOT / "config.yaml",
        help="Path to config.yaml (default: repo root config.yaml)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=REPO_ROOT / "apps/web/src/lib/categories.ts",
        help="Path to categories.ts output file",
    )
    args = parser.parse_args()

    categories = load_categories(args.config)
    output = render_categories_ts(categories)
    args.output.write_text(output, encoding="utf-8")
    print(f"Wrote {len(categories)} categories to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
