// Generated by scripts/sync_categories.py — do not edit manually.
// Source: config.yaml categories

export const CATEGORIES = [
  "Technical Research",
  "News Digests",
  "AI News",
  "Vendor News",
  "Governance and Policy",
  "Product Updates",
  "Education",
  "Other",
] as const;

export type Category = (typeof CATEGORIES)[number];

export const UNCATEGORIZED = "Uncategorized";
