// Generated by scripts/sync_web_vocab.py — do not edit manually.
// Source: config.yaml article_types and article_domains

export const ARTICLE_TYPES = [
  "research",
  "news",
  "governance",
  "opinion",
] as const;

export const ARTICLE_DOMAINS = [
  "LLMs",
  "optimisation",
  "computer vision",
  "RAG",
  "agents",
  "robotics",
  "ethics",
  "policy",
] as const;

export type ArticleType = (typeof ARTICLE_TYPES)[number];
export type ArticleDomain = (typeof ARTICLE_DOMAINS)[number];
